### ISSUE TITLE
Issue in the 2Warm CTF write up 

### ISSUE THREAD

**Issue by Noam-Alum** [ShayAviv/picoCTF-Writeups#1]
### Referring to:

![image](https://github.com/user-attachments/assets/9373eb02-b562-47a8-8891-23f1c83e98df)

**I.e. The image, and a misspelling. (Alternativly instead of Alternatively)**

---

### Potential fix:

```md
> Alternatively, if you want to solve it without a website you can manually subnet it:

    ![Screenshot](images/3.png)
```

**Comment by ShayAviv** [comment]
Being taken care of, thank you for noting it.
